language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install .
  - pip install coverage
  - pip install coveralls

script:
  - shcmd -h
  - pytest

after_success:
  - coverage run -m pytest
  - coverage report
  - coverage html

notifications:
   email:
      on_success: change
      on_failure: always
